# Generated by Django 5.2.3 on 2025-07-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('serial', models.IntegerField(unique=True)),
                ('forwhat', models.CharField(max_length=255)),
                ('response_type', models.CharField(choices=[('html', 'HTML'), ('text', 'Plain Text')], default='text', max_length=50)),
                ('response', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Commands',
            },
        ),
    ]
